### ISSUE TITLE
store uploaded image to cloudinary server

### ISSUE THREAD

**Issue by this-is-pooja** [this-is-pooja/cloudinary-upload#1]
Add functionality to successfully upload an image to cloudinary through API

**Comment by i-am-shashank** [comment]
@this-is-pooja assign this to me!

**Comment by this-is-pooja** [comment]
@this-is-shashank-mishra great, go ahed.

**Comment by i-am-shashank** [comment]
@this-is-pooja  I will need to divide the code into two parts, i.e **client, server** is that OK?

**Comment by this-is-pooja** [comment]
@this-is-shashank-mishra yes

**Comment by this-is-pooja** [comment]
good job
